In [2]:
#Consider the below code to answer further questions:
import numpy as np
list_ = [ "1","2","3","4","5"]
array_list = np.array(object = list_)

In [3]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [8]:
#answer1-
"""Yes, there is a difference in the data types of the variables list_ and array_list."""

'Yes, there is a difference in the data types of the variables list_ and array_list.'

In [9]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [10]:
list_

['1', '2', '3', '4', '5']

In [11]:
type(array_list)

numpy.ndarray

In [12]:
type(list_)

list

In [13]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [15]:
#answer2-
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [16]:
#Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [24]:
#Q3- Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [25]:
#answer3-
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [26]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [27]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
"""
Yes, there will be a difference in the data type of the elements present in both list_ and array_list after the change 
array_list = np.array(object = list_, dtype = int). The dtype=int argument specifies that the elements in the array_list 
should be converted to the integer data type.
"""

In [28]:
array_list = np.array(object = list_, dtype = int)
array_list

# Print the data type of each elements in the list
print("Data types in List_ : ")
for elements in list_ :
    print(type(eliments))

# Print the data tpes of each elements in the NumPy array  
print("\nData types in array_list : ")
for elements in array_list :
    print(type(elements))

Data types in List_ : 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list : 
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [29]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [30]:
#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size

In [31]:
#answer4-
#(i)- 
np.shape(num_array)

(2, 3)

In [32]:
#(ii)-
np.size(num_array)

6

In [33]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

#[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [36]:
#answer5-
ar = np.zeros((3,3))
print(ar)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [37]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?

#[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [38]:
#answer6-
# Uding the below code we can create the identity matrix of 5 eliments 1 and other id 0
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
